services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: duwniy
      POSTGRES_PASSWORD: duwniy00
      POSTGRES_DB: bereal
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"   # хост:контейнер

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bereal  # внутренний порт контейнера
      SPRING_DATASOURCE_USERNAME: duwniy
      SPRING_DATASOURCE_PASSWORD: duwniy00
    ports:
      - "8080:8080"

volumes:
  db_data:
